name = "discovery-convoy-auth"
main = "index.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "discovery_convoy_auth"
database_id = "85ee9b2f-ba0e-4146-8d8f-94c062cc6bf0"
